title: Home Link
theme: minima
author: grayTurtle01
email: the.correo@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is static site to test jekyll and Github
  
# social links
twitter_username: mercenario
github_username:  grayTurtle01

show_excerpts: false # set to false to remove excerpts on the homepage
